version: "3.8"

services:
  app:
    image: ${{ secrets.ECR_REGISTRY }}/fastapi-app:latest
    container_name: fastapi-app
    ports:
      - "8000:8000"
    restart: always  # Ensures container restarts if it crashes

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always  # Ensures Nginx restarts if it crashes
