version: "3.8"

services:
  app:
    image: fastapi-app:latest  # Use a placeholder image, updated in the deployment script
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
