name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Tag and Push Docker image
        run: |
          docker tag fastapi-app ${{ secrets.ECR_REGISTRY }}/fastapi-app:latest
          docker push ${{ secrets.ECR_REGISTRY }}/fastapi-app:latest

      - name: Deploy to EC2 using Docker Compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/fastapi-book-project || exit

            # Pull latest code without resetting (prevents breaking changes)
            git pull origin main

            # Update docker-compose.yml with the correct ECR image
            sed -i 's|image: fastapi-app|image: ${{ secrets.ECR_REGISTRY }}/fastapi-app:latest|g' docker-compose.yml

            # Login to AWS ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

            # Pull the latest FastAPI image
            docker-compose pull

            # Stop running containers (if any)
            docker-compose down

            # Clean up old Docker images
            docker system prune -af || true

            # Restart Docker Compose to apply updates
            docker-compose up -d --pull always --force-recreate --remove-orphans

            echo "Deployment Successful using Docker Compose! 🚀"
