name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # ✅ Login to AWS ECR
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      # ✅ Build Docker image
      - name: Build Docker image
        run: docker build -t fastapi-app .

      # ✅ Tag and push image to AWS ECR
      - name: Push Docker image to AWS ECR
        run: |
          docker tag fastapi-app ${{ secrets.ECR_REGISTRY }}/fastapi-app:latest
          docker push ${{ secrets.ECR_REGISTRY }}/fastapi-app:latest

      # ✅ Deploy to AWS EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            #Navigate to project directory
            cd /home/ubuntu/fastapi-book-project

            #Pull latest code from Github
            git reset --hard
            git pull origin main

            # Login to AWS ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

            # aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

            # Pull the latest image
            docker pull ${{ secrets.ECR_REGISTRY }}/fastapi-app:latest

            # Stop and remove the old container
          
            docker stop fastapi-app || true
            docker rm fastapi-app || true

            # Check if port 8000 is in use and free it
            if lsof -i :8000; then
            echo "Port 8000 is in use. Stopping the process..."
            fuser -k 8000/tcp  # Kill any process using port 8000
            fi

            # Run the new container
            docker run -d -p 8000:8000 --name fastapi-app ${{ secrets.ECR_REGISTRY }}/fastapi-app:latest

            # Reload systemd daemon to prevent Nginx warning
            sudo systemctl daemon-reload

            # Restart Nginx
            sudo systemctl restart nginx

            echo "Deployment Successful! o"


